rootDir = '/misc/lmbraid21/jesslen/StarMap/'
pascal3dDir = '/misc/lmbraid21/jesslen/StarMap/data/PASCAL3D/PASCAL3D+_release1.1/'
ObjectNet3DPath = '/misc/lmbraid21/jesslen/StarMap/data/ObjectNet3D/ObjectNet3D_source/'
# rootDir = '/home/angtian/angtian/workspace/StarMap/'
# pascal3dDir = '/home/angtian/angtian/workspace/PASCAL3D/PASCAL3D+_release1.1/'
# ObjectNet3DPath = '/home/angtian/angtian/workspace/ObjectNet3D/ObjectNet3D_source/'